BetterLectio/betterLectio

src/routes/+layout.svelte, src/routes/fri/+page.svelte, src/routes/værktøjer/+page.svelte
A new tab in the nav, to be expanded upon
=> countdown to end of class

src/components/Avatar.svelte
=> Avatar placeholder på dem som ikke har navn

src/routes/skema/+page.svelte, yarn.lock
=> added dagsnoter

src/routes/fravær/+page.svelte
Matcher table style fra opgave tablen. Ser også godt på mobil ud.
=> Pænere fravær table

src/routes/fravær/+page.svelte
https://jth.photos/firefox_Ci4ylcR4ia.gif
=> Fravær moduler og kolonnesortering

package-lock.json, package.json, src/routes/fravær/+page.svelte, tailwind.config.cjs, yarn.lock
Simpel grafisk fraværoversigt med graph.js
https://jth.photos/firefox_rjOQba3dxz.gif
=> Grafisk fraværoversigt

src/routes/dokumenter/+page.svelte
=> Filtype ikoner til dokumenter.

src/routes/auth/+page.svelte
Ved ikke om i er enige, men jeg har brug for at kunne trykke enter for at "submitte"..
Og det er også bedre accesibility. Så kan man diskutere om min løsning er god, og om man så ikke også skal kunne gå fra username til password med enter.
=> Log ind når man trykker enter i password feltet.

src/routes/værktøjer/+page.svelte, src/routes/værktøjer/fravær/+page.svelte
https://jth.photos/firefox_SIScLAhHHJ.mp4
=> Fravær regner

src/components/CookieInfo.js
Fixes issue #88 
Changed atob to window.atob
Fix/workarround form here: https://github.com/microsoft/TypeScript/issues/45566
=> Fixed the atob depreciation issue 

src/routes/auth/+page.svelte
1password kunne ikke genkende brugernavn id, så jeg har ændret det til username, så det virker nu.
Løsning fra: https://developer.1password.com/docs/web/compatible-website-design
=> Fixed the username id, so password managers recognise it now

src/routes/fravær/+page.svelte, src/routes/værktøjer/fravær/+page.svelte, yarn.lock
Det giver lidt sig selv hvad det gør.
=> Fixed fravær sider

src/components/Spinner.svelte, src/routes/værktøjer/fri/+page.svelte
Nu spammer den ikke APIen hvert sekund, lol.
Den ignorerer også nogle moduler, skal nok opdateres på et tidspunkt:
=> Fri counter rewrite

src/routes/fravær/+page.svelte
Lidt uheldig fejl, men meget let at fikse :)
=> Manglende fraværsårsager fix

src/routes/værktøjer/fravær/+page.svelte
https://jth.photos/firefox_iY3rwef2b5.gif
=> Better fravær værktøj

src/routes/fravær/+page.svelte
=> Fix manglende fraværsårsager check

src/routes/lektier/+page.svelte
Inkluderer cases til "I dag" og "I morgen".
=> Bedre datoer til lektier

src/lib/js/store.js, src/routes/forside/+page.svelte, src/routes/værktøjer/+page.svelte, src/routes/værktøjer/eksamener/+page.svelte
=> Tilføjet eksamener til værktøjer og forside

src/app.css, src/lib/components/BrugerPopupWindow.svelte, src/lib/components/GlobalSearch.svelte, src/lib/components/NavBar.svelte, src/lib/components/SideBar.svelte, src/lib/components/StandaloneModul.svelte, src/lib/components/Table.svelte, src/lib/js/LectioCookieHandler.js, src/lib/js/LectioUtils.js, src/lib/js/http.js, src/routes/+layout.svelte, src/routes/auth/+page.svelte, src/routes/beskeder/+page.svelte, src/routes/dokumenter/+page.svelte, src/routes/forside/+page.svelte, src/routes/fravær/+page.svelte, src/routes/indstillinger/routes/Generelt.svelte, src/routes/indstillinger/routes/Konto.svelte, src/routes/karakterer/+page.svelte, src/routes/modul/+page.svelte, src/routes/opgave/+page.svelte, src/routes/opgaver/+page.svelte, src/routes/skema/+page.svelte, src/routes/værktøjer/+page.svelte, src/routes/værktøjer/fravær/+page.svelte, src/routes/værktøjer/fri/+page.svelte, src/routes/værktøjer/googlecalsync/+page.svelte
fix: fix eslint errors 
refactor: rename school to schoolId
refactor: rename userid to userId
feat: add days and seperate modules on forside
fix: address bugs in fravaer
feat: karakterer default så strukturen loader
fix: søg was different font size 
feat: add PageLoading to fravær
=> Fixes og bedre modul-display på forsiden

package.json, src/routes/+layout.svelte
=> Mobil opdatering

src/lib/components/StandaloneModul.svelte, src/lib/js/HoldOversætter.js, src/routes/+layout.svelte, src/routes/fravær/+page.svelte, src/routes/skema/+page.svelte, src/routes/værktøjer/fri/+page.svelte
OBS husk nu at følge eslint reglerne når I koder, ellers klager formatteren!
=> Mere arbejde på StandaloneModul og fiks bug issue

.gitignore, package-lock.json, package.json, src/hooks.client.js, src/hooks.server.js, src/routes/tos/+page.svelte, vite.config.js
This pull request adds a Sentry configuration file and plugin for SvelteKit, allowing for automatic error reporting. It also updates the privacy policy to include information about the use of Sentry.
=> Add Sentry config file and plugin for SvelteKit, update privacy policy

apps/auth-sync-server/package-lock.json, apps/auth-sync-server/package.json, apps/depricated/package-lock.json, apps/depricated/package.json, apps/frontend/package-lock.json, apps/frontend/package.json, apps/frontend/src/lib/stores.ts, apps/frontend/src/routes/indstillinger/+page.svelte, apps/frontend/src/routes/opgaver/+page.svelte, apps/landing-page/package-lock.json, apps/landing-page/package.json
* [`apps/frontend/src/lib/stores.ts`](diffhunk://#diff-a2c16e4abaeda67655678695a01985d54b248fdbbe2f372be4bfe91b86e753edL1-R105): Standardized import statements and added `assignmentsPageSettingsStore`.
* [`apps/frontend/src/routes/indstillinger/+page.svelte`](diffhunk://#diff-2319702793c18fe3c39aa70fac7d9fc893569247719d1a1e3468f09f99e1cebfL9-R9): Imported `assignmentsPageSettingsStore` and added UI elements for filtering assignments. [[1]](diffhunk://#diff-2319702793c18fe3c39aa70fac7d9fc893569247719d1a1e3468f09f99e1cebfL9-R9) [[2]](diffhunk://#diff-2319702793c18fe3c39aa70fac7d9fc893569247719d1a1e3468f09f99e1cebfR150-R164)
* [`apps/frontend/src/routes/opgaver/+page.svelte`](diffhunk://#diff-05f307b2cde3ebaf0ee1ade84ca33580fdfb1fab65ebbb52d7a778b5e36e88a8L11-R11): Added logic to filter …
=> fixes: Afleveringer #272
